version: 2
updates:
  # 监控 GitHub Actions 插件版本
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "08:00"
    open-pull-requests-limit: 3 # 限制同时开启的 PR 数量，防止刷屏

  # 监控 Python 依赖包 (如 requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
      time: "09:00"
    open-pull-requests-limit: 3
