name: Convert Surge Rules to Clash Verge

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Convert Surge Rules to Clash Verge
        uses: ./.github/actions/convert-surge-to-clash
        with:
          surge_rules_path: conf/rule/surge/
          clash_rules_path: conf/rule/clash/


