name: Convert Surge Rules to Clash Verge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0  # 使用特定版本

      - name: Set up Python
        uses: actions/setup-python@v4  # 更新到 v4
        with:
          python-version: '3.x'

      - name: Run conversion script
        run: |
          python3 conf/script/convert_surge_to_clash.py

      - name: Commit files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add conf/rule/clash/
          git commit -m 'Automated conversion of Surge rules to Clash Verge'
          git push

